jobs:
  - job: ios
    displayName: iOS
    pool:
      vmImage: macos-11
    strategy:
      matrix:
        armv8:
          args: "-a armv8 -p ios"
        armv8.3:
          args: "-a armv8.3 -p ios"
        x86_64:
          args: "-a x86_64 -p ios"
    steps:
      - bash: >
          brew install cmake conan
        displayName: Install the necessary packages
      - template: ./conan.yml
        parameters:
          buildArgs: $(args) -v 15.0
