jobs:
  - job: ubuntu
    displayName: Ubuntu 20.04
    pool:
      vmImage: ubuntu-20.04
    strategy:
      matrix:
        static_debug:
          args: "-d"
        static_release:
          args: ""
        dynamic_debug:
          args: "-ds"
        dynamic_release:
          args: "-s"
    steps:
      - bash: >
          sudo apt install -y cmake g++ git patch python3-pip
        displayName: Install the necessary packages
      - bash: >
          sudo pip install conan
        displayName: Inatall Conan
      - template: ./conan.yml
        parameters:
          buildArgs: $(args)
