jobs:
  - job: windows
    displayName: Windows 2019
    pool:
      vmImage: windows-2019
    strategy:
      matrix:
        debug:
          args: "-dp windows"
        release:
          args: "-p windows"
    steps:
      - powershell: >
          choco install -y conan
        displayName: Install conan
      - template: ./conan.yml
        parameters:
          buildArgs: $(args)
